# Generated by Django 5.1.3 on 2024-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_clone_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
